# Generated by Django 5.0.4 on 2024-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('Asus', 'Asus'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='memory',
            field=models.PositiveIntegerField(default=1, help_text='Memory in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='operation_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux'), ('Chrome OS', 'Chrome OS')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.PositiveIntegerField(default=1, help_text='Storage in GB'),
            preserve_default=False,
        ),
    ]
