# Generated by Django 5.0.4 on 2024-06-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_in',
            new_name='created_on',
        ),
    ]
