# Generated by Django 5.0.4 on 2024-07-02 09:38

from django.db import migrations


# from main_app.models import Shoe

def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')

    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    ubn = shoe.objects.values_list('brand', flat=True).distinct()

    # for brand_name in ubn:
    #     unique_brands.create(brand_name=brand_name)  # insert into unique_brands(brand_name) values (brand_name)
    unique_brands.objects.bulk_create([unique_brands(brand=brand_name) for brand_name in ubn])  # more optimal way


def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_unique_brands)
    ]
